- name: Configure all servers
  hosts: all
  become: yes
  vars_files:
    - ../group_vars/{{ group_names[0] }}.yml
    - ../group_vars/vault.yml
    - ../group_vars/all.yml

  roles:
    - users
    - common
    - docker
    - nginx
